run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
#    - errcheck
    - ineffassign
    - gosimple
    - typecheck
    - unused
    - misspell
    - gosec
    - goconst
    - exportloopref
    - rowserrcheck
    - unconvert
    - unparam
    - prealloc
    - errname
    - contextcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # Suppress gosec G115 (int->uint overflow) only in test files
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
      text: ^G115
